import type { Metadata, Viewport } from 'next'
import { Archivo, JetBrains_Mono, Sora } from 'next/font/google'
import type { ReactNode } from 'react'

import { Footer } from '@/components/chrome/Footer'
import { Nav } from '@/components/chrome/Nav'
import { ScrollProgress } from '@/components/chrome/ScrollProgress'
import { searchIndexable } from '@/config/env'
import { profile, visibleSections } from '@/content'
import { palette } from '@/lib/brand/palette'
import { jsonLdScript } from '@/lib/seo/jsonLd'
import {
  siteDescription,
  siteKeywords,
  siteName,
  siteUrl,
} from '@/lib/seo/site'

import './globals.css'

/**
 * Fonts are downloaded at BUILD time and served from our own origin — there
 * is no request to Google at runtime, so the site makes zero third-party
 * requests and leaks nothing about visitors.
 *
 * Each exposes a CSS variable that globals.css maps onto a design token, so
 * components only ever name `font-display`, `font-body`, or `font-mono`.
 */
const sora = Sora({
  subsets: ['latin'],
  // 700 is used by five headings — the hero's line, every section heading,
  // project titles — and was missing, so the browser was synthesising a fake
  // bold for all of them. 300 was loaded and used nowhere. Swapping the two
  // costs no extra bytes and fixes the type everywhere at once.
  weight: ['400', '600', '700', '800'],
  variable: '--font-sora',
  display: 'swap',
})

const archivo = Archivo({
  subsets: ['latin'],
  weight: ['400', '500', '600'],
  variable: '--font-archivo',
  display: 'swap',
})

const jetbrains = JetBrains_Mono({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-jetbrains',
  display: 'swap',
})

/**
 * Every field here is derived — see src/lib/seo/site.ts. The social card
 * itself is generated by opengraph-image.tsx and picked up automatically, so
 * `openGraph.images` is deliberately not set: naming it here would be a
 * second place for the card's URL to be wrong.
 */
export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: { default: siteName, template: `%s — ${profile.name}` },
  description: siteDescription,
  keywords: [...siteKeywords],
  applicationName: siteName,
  authors: [{ name: profile.name, url: siteUrl }],
  creator: profile.name,
  publisher: profile.name,
  alternates: { canonical: '/' },
  // The CV carries a phone number that the site deliberately does not
  // publish; this stops iOS inventing tel: links out of other digits.
  formatDetection: { telephone: false, address: false, email: false },
  openGraph: {
    type: 'website',
    url: '/',
    siteName,
    title: siteName,
    description: siteDescription,
    locale: 'en_IN',
  },
  twitter: {
    card: 'summary_large_image',
    title: siteName,
    description: siteDescription,
  },
  robots: searchIndexable
    ? {
        index: true,
        follow: true,
        googleBot: {
          index: true,
          follow: true,
          'max-image-preview': 'large',
          'max-snippet': -1,
          'max-video-preview': -1,
        },
      }
    : { index: false, follow: false },
}

export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  // Read from the stylesheet that defines it, so the browser chrome and the
  // page can never be two different shades of the same colour.
  themeColor: palette.ground,
}

export default function RootLayout({ children }: { children: ReactNode }) {
  const fontVariables = `${sora.variable} ${archivo.variable} ${jetbrains.variable}`

  return (
    <html lang="en" className={`${fontVariables} h-full`}>
      <head>
        {/*
          Marks that scripting is available, before the first paint. Every
          scroll-reveal's hidden start state is scoped to this class, so a
          blocked or failed bundle leaves the page fully readable instead of
          blank. Inline and synchronous on purpose — deferring it would show
          a flash of un-hidden content.
        */}
        <script
          dangerouslySetInnerHTML={{
            __html: `document.documentElement.classList.add('js')`,
          }}
        />

        {/*
          Structured data: the machine-readable version of the same CV the
          page renders. Built from the content layer, so it cannot describe a
          job or an award that is not also on the page.
        */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: jsonLdScript() }}
        />
      </head>
      <body className="flex min-h-full flex-col">
        {/* R8 — keyboard users skip the nav without tabbing through it. */}
        <a
          href="#main"
          className="bg-accent text-ink sr-only rounded-edge px-4 py-2 font-mono text-xs focus:not-sr-only focus:absolute focus:top-4 focus:left-4 focus:z-100"
        >
          Skip to content
        </a>

        <ScrollProgress />
        <Nav
          items={visibleSections}
          owner={profile.name}
          action={{ label: 'Get in touch', sectionId: 'contact' }}
        />

        <div id="top" className="relative z-10 flex flex-1 flex-col">
          {children}
        </div>

        <Footer
          items={visibleSections}
          links={profile.links}
          owner={profile.name}
          year={new Date().getFullYear()}
        />
      </body>
    </html>
  )
}
